# Generated by Django 5.0.1 on 2024-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Printer', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toner_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_name', models.CharField(max_length=500)),
                ('Department', models.CharField(choices=[('IT', 'it'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('PENSION', 'Pension'), ('INDIVIDUAL LIFE', 'Individual life'), ('LIFE ACCOUNTS', 'Life accounts'), ('C.O.O', 'C.O.O'), ('G.M', 'G.M'), ('M.D', 'M.D'), ('BRANCH 2', 'Branch 2'), ('BRANCH 1', 'Branch 2'), ('UNDEWRITING HUB', 'Underwriting Hub'), ('HR', 'HR'), ('REINSURANCE', 'Reinsurance'), ('DSF', 'DSF'), ('AUDIT', 'Audit'), ('ACTURIAL', 'Acturial'), ('CLAIMS MOTOR', 'Claims motor'), ('CLAIMS MEDICAL', 'Claims medical'), ('LEGAL', 'legal'), ('CUSTOMER CARE', 'Customer care')], default='LIFE ACCOUNTS', max_length=100)),
                ('Location', models.CharField(choices=[('HEAD OFFICE', 'head office'), ('WESTLANDS', 'westlands'), ('ENTERPRISE ROAD', 'enterprise road'), ('NAKURU', 'nakuru'), ('ELDORET', 'eldoret'), ('KISUMU', 'kisumu'), ('MOMBASA', 'mombasa'), ('KISII', 'kisii'), ('NYERI', 'nyeri'), ('THIKA', 'thika'), ('MERU', 'meru'), ('MACHAKOS', 'machakos')], default='HEAD OFFICE', max_length=100)),
            ],
        ),
    ]
