# Generated by Django 5.0.1 on 2024-01-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner_request',
            name='Toner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.toner'),
        ),
    ]
