# Generated by Django 5.0.1 on 2024-01-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0002_toner_request_toner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='Toner',
            field=models.CharField(default='Y', max_length=500),
        ),
    ]
