# Generated by Django 5.0.1 on 2024-01-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0004_remove_toner_name_alter_toner_toner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Printer_name', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='toner',
            name='Printer',
        ),
        migrations.AlterField(
            model_name='toner_request',
            name='Department',
            field=models.CharField(choices=[('IT', 'it'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('PENSION', 'Pension'), ('INDIVIDUAL LIFE', 'Individual life'), ('LIFE ACCOUNTS', 'Life accounts'), ('C.O.O', 'C.O.O'), ('G.M', 'G.M'), ('M.D', 'M.D'), ('BRANCH 2', 'Branch 2'), ('BRANCH 1', 'Branch 1'), ('UNDEWRITING HUB', 'Underwriting Hub'), ('HR', 'HR'), ('REINSURANCE', 'Reinsurance'), ('DSF', 'DSF'), ('AUDIT', 'Audit'), ('ACTURIAL', 'Acturial'), ('CLAIMS MOTOR', 'Claims motor'), ('CLAIMS MEDICAL', 'Claims medical'), ('LEGAL', 'legal'), ('CUSTOMER CARE', 'Customer care')], default='LIFE ACCOUNTS', max_length=100),
        ),
        migrations.AddField(
            model_name='toner',
            name='printer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.printer'),
        ),
        migrations.AddField(
            model_name='toner_request',
            name='printer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.printer'),
        ),
    ]
