# Generated by Django 5.0.1 on 2024-01-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0005_printer_remove_toner_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner_request',
            name='Staff_ID',
            field=models.CharField(default='', max_length=500),
        ),
    ]
