# Generated by Django 5.0.1 on 2024-01-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0006_toner_request_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner_request',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
