# Generated by Django 5.0.1 on 2024-01-11 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0007_toner_request_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner_request',
            name='Date_of_request',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 11, 12, 20, 34, 800335, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
