# Generated by Django 5.0.1 on 2024-01-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0010_alter_toner_request_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner_request',
            name='Staff_ID',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
